# Generated by Django 4.1.7 on 2023-03-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_athlete_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
