# Generated by Django 4.1.7 on 2023-03-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_athlete_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='club_name',
            field=models.CharField(default='UNK', max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='coach_name',
            field=models.CharField(default='UNK', max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='fighting_style',
            field=models.CharField(default='UNK', max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='record',
            field=models.CharField(default='UNK', max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=4),
        ),
    ]
