# Generated by Django 4.1.7 on 2023-03-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_athlete_age_alter_athlete_club_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='contact_number',
            field=models.CharField(default='eg. 9843029462', max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='date_of_birth',
            field=models.DateField(default='2011-1-1'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(default='FirstName MiddleName LastName', max_length=100),
        ),
    ]
