# Generated by Django 4.1.7 on 2023-03-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_athlete_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='profile_picture',
            field=models.ImageField(default='Combat_conog/default_img.png', upload_to='athlete_pics/'),
        ),
    ]
