# Generated by Django 4.1.7 on 2023-03-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_athlete_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(default='FirstName MiddleName LastName', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(default='FIRSTNAME MIDDLENAME LASTNAME', max_length=100, unique=True),
        ),
    ]
