# Generated by Django 4.1.7 on 2023-03-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_athlete_name_alter_host_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='events_hosted',
            field=models.IntegerField(default=1),
        ),
    ]
