# Generated by Django 4.1.7 on 2023-04-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_athlete_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='club_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='coach_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='fighting_style',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='record',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
