# Generated by Django 4.1.7 on 2023-04-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_athlete_age_alter_athlete_club_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='club_name',
            field=models.CharField(default='UNK', max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='coach_name',
            field=models.CharField(default='UNK', max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='date_of_birth',
            field=models.DateField(default='2011-1-1'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='fighting_style',
            field=models.CharField(default='UNK', max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='record',
            field=models.CharField(default='UNK', max_length=100),
        ),
    ]
