# Generated by Django 4.1.7 on 2023-04-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_athlete_club_name_alter_athlete_coach_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='name',
        ),
        migrations.RemoveField(
            model_name='host',
            name='name',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='club_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='coach_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='fighting_style',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='athlete_pics/'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='record',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=4),
        ),
        migrations.AlterField(
            model_name='host',
            name='events_hosted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
    ]
