# Generated by Django 4.1.7 on 2023-04-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_athlete_name_remove_host_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='club_name',
            field=models.CharField(default='UNK', max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='coach_name',
            field=models.CharField(default='UNK', max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='date_of_birth',
            field=models.DateField(default='2011-1-1'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='fighting_style',
            field=models.CharField(default='UNK', max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='record',
            field=models.CharField(default='UNK', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
