# Generated by Django 4.1.7 on 2023-04-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_athlete_club_name_alter_athlete_coach_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_img.png', null=True, upload_to='athlete_pics/'),
        ),
    ]
