# Generated by Django 4.1.7 on 2023-04-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_athlete_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='name',
            field=models.CharField(default='N/S', max_length=100),
        ),
        migrations.AddField(
            model_name='host',
            name='name',
            field=models.CharField(default='N/S', max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='contact_number',
            field=models.CharField(default='eg. 9843029462', max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='athlete_pics/'),
        ),
        migrations.AlterField(
            model_name='host',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
