# Generated by Django 4.1.7 on 2023-04-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_athlete_name_host_name_alter_athlete_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='contact_number',
            field=models.IntegerField(default='9843029462', max_length=10),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='profile_picture',
            field=models.ImageField(blank=True, default='C:\\SHRUTI\\SEM_6\\PROJECT\\Combat_conog\\default_img.png', null=True, upload_to='athlete_pics/'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight_category',
            field=models.CharField(choices=[('Strawweight', 'Strawweight'), ('Flyweight', 'Flyweight'), ('Bantamweight', 'Bantamweight'), ('Featherweight', 'Featherweight'), ('Lightweight', 'Lightweight'), ('Super Lightweight', 'Super Lightweight'), ('Welterweight', 'Welterweight'), ('Super Welterweight', 'Super Welterweight'), ('Middleweight', 'Middleweight'), ('Super Middleweight', 'Super Middleweight')], max_length=20),
        ),
        migrations.AlterField(
            model_name='host',
            name='contact_number',
            field=models.IntegerField(default='9843029462', max_length=10),
        ),
    ]
