# Generated by Django 4.1.7 on 2023-04-14 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_athlete_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='contact_number',
            field=models.IntegerField(default='9843029462', validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='host',
            name='contact_number',
            field=models.IntegerField(default='9843029462', validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
