# Generated by Django 4.1.7 on 2023-04-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_athlete_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
    ]
