# Generated by Django 4.1.7 on 2023-03-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_alter_athlete_name_alter_host_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('last_reg_date', models.DateField()),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contact_no', models.CharField(max_length=20)),
                ('ig_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('fb_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.host')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='registered_athletes',
            field=models.ManyToManyField(through='events.Registration', to='users.athlete'),
        ),
    ]
