# Generated by Django 4.1.7 on 2023-03-09 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_host_events_hosted'),
        ('events', '0002_registration_age_registration_club_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default='MUKTA HEMANT BARVE', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='users.host'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registered_athletes',
            field=models.ManyToManyField(related_name='registrations', through='events.Registration', to='users.athlete'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='athlete',
            field=models.ForeignKey(default='GAURI BARVE', on_delete=django.db.models.deletion.CASCADE, to='users.athlete'),
        ),
    ]
