# Generated by Django 4.1.7 on 2023-04-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_athlete_age_alter_athlete_club_name_and_more'),
        ('events', '0003_alter_event_host_alter_event_registered_athletes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='users.host'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.athlete'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='club_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fighting_style',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30),
        ),
        migrations.AlterField(
            model_name='registration',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='registration',
            name='weight_category',
            field=models.CharField(choices=[('Straw Weight', 'Straw Weight'), ('Fly Weight', 'Fly Weight'), ('Bantam Weight', 'Bantam Weight')], max_length=30),
        ),
    ]
